# permissions for end users to edit hazelcasts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hazelcast-editor-role
rules:
- apiGroups:
  - charts.my.domain
  resources:
  - hazelcasts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.my.domain
  resources:
  - hazelcasts/status
  verbs:
  - get
