apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: operator
rules:
- apiGroups:
    - ""
  resources:
    - secrets
    - pods
    - pods/exec
    - pods/log
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - apps
  resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
  - hazelcast.my.domain
  resources:
  - hazelcasts
  verbs:
  - "*"
- apiGroups:
  - hazelcast.my.domain
  resources:
    - hazelcasts
    - hazelcasts/status
    - hazelcasts/finalizers
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "get"
  - "list"
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator
subjects:
- kind: ServiceAccount
  name: operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: operator
  apiGroup: ""