apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
spec:
  selector:
    matchLabels:
      app: operator
  replicas: 1
  template:
    metadata:
      labels:
        app: operator
    spec:
      containers:
        - image: leszko/hazelcast-operator:java
          name: hazelcast-operator
          imagePullPolicy: Always